<div class="jumbotron">

    This is hello world for jumbotron from TgePageLayout module

</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sample</h3>
            </div>
            <div class="panel-body">
                <p>Hello world from TgePageLayout module from view/tge-page-layout/index/index.phtml</p>
            </div>
        </div>
    </div>

    <?php echo $this->widget; ?>

</div>
