    <!-- custom dynamical widget -->
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">dynamical widget title: <?php echo $this->title; ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->content; ?></p>
            </div>
        </div>
    </div>