<div class="jumbotron">

This is hello world for jumbotron from TgeHelloWorld module

</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sample</h3>
            </div>
            <div class="panel-body">
                <p>Hello world from TgeHelloWorld module from view/tge-hello-world/index/index.phtml</p>
            </div>
        </div>
    </div>

</div>
